/**
 * The browser-safe subset of the environment, rendered as public/assets/js/env.js (window.__ENV).
 * Shared by scripts/build.mjs (static file for Vercel) and scripts/dev-server.mjs (served live so a
 * changed .env or a test override is picked up without a rebuild).
 */
import { existsSync, readFileSync } from 'node:fs';

export const PUBLIC_KEYS = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'TURNSTILE_SITE_KEY', 'SENTRY_DSN', 'SITE_URL', 'COURSE_RELEASED'];

export function readDotEnv(file) {
  if (!existsSync(file)) return {};
  const o = {};
  for (const line of readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/i);
    if (!m || line.trim().startsWith('#')) continue;
    o[m[1]] = m[2].replace(/^(["'])(.*)\1$/, '$2');
  }
  return o;
}

/** process.env wins over .env so CI / test runners can override without touching the file. */
export function publicEnv(dotEnvFile) {
  const env = { ...readDotEnv(dotEnvFile), ...process.env };
  const pub = {};
  for (const k of PUBLIC_KEYS) pub[k] = env[k] || '';
  for (const k of Object.keys(pub)) {
    if (/SERVICE_ROLE|SECRET|API_KEY|TOKEN/i.test(k)) throw new Error(`refusing to expose ${k} to the browser`);
  }
  return pub;
}

export function publicEnvScript(dotEnvFile) {
  return `// Generated by scripts/build.mjs from .env — public keys only.\nwindow.__ENV = ${JSON.stringify(publicEnv(dotEnvFile), null, 2)};\n`;
}
