/**
 * Seed public.email_templates from emails/templates.json (one row per template and language).
 *
 *   pnpm seed              # upsert into the project in .env (service role)
 *   pnpm seed -- --sql     # only regenerate supabase/seed.sql (no .env needed)
 *
 * Arabic rows are the English spec with the template's `ar` overrides applied and lang = 'ar', which is
 * exactly what the admin "Email templates" page writes (the server sender renders from emails/templates.json).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SEED_SQL = join(ROOT, 'supabase', 'seed.sql');

type Spec = Record<string, unknown> & { file: string; name: string; kind?: string; trigger?: string; ar?: Record<string, unknown> };
interface Row { id: string; name: string; kind: string; trigger: string | null; spec: Record<string, unknown>; lang: 'en' | 'ar' }

export function templateRows(specs: Spec[]): Row[] {
  const rows: Row[] = [];
  for (const spec of specs) {
    const base = { id: spec.file, name: spec.name, kind: spec.kind || 'auto', trigger: spec.trigger || null };
    rows.push({ ...base, lang: 'en', spec: { ...spec, lang: 'en' } });
    if (spec.ar) {
      const { ar, ...en } = spec;
      rows.push({ ...base, lang: 'ar', spec: { ...en, ...ar, lang: 'ar' } });
    }
  }
  return rows;
}

function sqlString(v: string | null): string {
  return v == null ? 'null' : `'${v.replace(/'/g, "''")}'`;
}

export function seedSql(rows: Row[]): string {
  const values = rows
    .map((r) => `  (${sqlString(r.id)}, ${sqlString(r.name)}, ${sqlString(r.kind)}, ${sqlString(r.trigger)}, ${sqlString(r.lang)}, $json$${JSON.stringify(r.spec)}$json$::jsonb)`)
    .join(',\n');
  return [
    '-- Generated by `pnpm seed -- --sql` from emails/templates.json. Do not edit by hand.',
    '-- Apply with: supabase db push && psql "$SUPABASE_DB_URL" -f supabase/seed.sql   (or `pnpm seed` over the API)',
    '',
    '-- ---------------------------------------------------------------------',
    '-- Admin user',
    '-- ---------------------------------------------------------------------',
    '-- Profiles are created by the on_auth_user_created trigger when someone signs up, so the admin is',
    '-- promoted, not inserted. After the first admin has signed up and confirmed their email, run:',
    "--   select public.set_admin('admin@your-domain.com', true);",
    '-- /admin/ answers 404 to everyone else (middleware.ts + RLS via public.is_admin()).',
    '',
    '-- ---------------------------------------------------------------------',
    `-- Email templates (${rows.length} rows: ${rows.filter((r) => r.lang === 'en').length} templates x en/ar)`,
    '-- ---------------------------------------------------------------------',
    'insert into public.email_templates (id, name, kind, trigger, lang, spec) values',
    values,
    'on conflict (id, lang) do update set',
    '  name = excluded.name,',
    '  kind = excluded.kind,',
    '  trigger = excluded.trigger,',
    '  spec = excluded.spec,',
    '  updated_at = now();',
    '',
  ].join('\n');
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const specs = JSON.parse(readFileSync(join(ROOT, 'emails', 'templates.json'), 'utf8')) as Spec[];
  const rows = templateRows(specs);
  writeFileSync(SEED_SQL, seedSql(rows));
  console.log(`supabase/seed.sql: ${rows.length} template rows`);

  if (!process.argv.includes('--sql')) {
    const { adminClient } = await import('../src/lib/server/supabase.ts');
    const sb = adminClient();
    const { error } = await sb.from('email_templates').upsert(rows.map((r) => ({ ...r, updated_at: new Date().toISOString() })), { onConflict: 'id,lang' });
    if (error) {
      console.error('email_templates upsert failed:', error.message);
      process.exit(1);
    }
    console.log(`email_templates: ${rows.length} rows upserted into ${process.env.SUPABASE_URL}`);
  }
}
